Traceback (most recent call last):
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\user\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
@testset begin
  @test spectral_density(arma, two_pi=false)[2][4] â‰ˆ 0.16077100233347555
  # As before, we need to repeat the calculations, since we don't have access to the results.
  @test (autocovariance(arma))[3] â‰ˆ -0.5886222919837174
  @test (impulse_response(arma))[10] == -0.004296875
  Random.seed!(42)
  @test (simulation(arma))[20] â‰ˆ -1.1975340216436439
end
------------------

[91mSome tests did not pass: 3 passed, 1 failed, 0 errored, 0 broken.[39m

Stacktrace:
 [1] finish(::Test.DefaultTestSet) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Test\src\Test.jl:879
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Test\src\Test.jl:1125
 [3] top-level scope at In[13]:2
 [4] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
LoadError: [91mSome tests did not pass: 3 passed, 1 failed, 0 errored, 0 broken.[39m

